CREATE TABLE IF NOT EXISTS usuarios (
    id INT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,

); 

CREATE TABLE IF NOT EXISTS alunos(
    nome VARCHAR(255) NOT NULL,
    idade INT NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    matricula VARCHAR (20) NOT NULL PRIMARY KEY,
);
